version: "3.8"

services:
  claim-portal-fe:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: claim-portal-fe-dev
    restart: unless-stopped
    ports:
      - "3043:3000"
    # env_file:
    #   - .env.local
